### PR TITLE
1.19.3 minimal viable version

### PR DESCRIPTION
**Pull request by Binero**
I have no idea what I am doing - but if you disable secure chat this works. Probably very much not release-ready.

### CODE REVIEW

**Comment by Binero** [comment]
Apparently this now works with secure chat enabled.

**Comment by Binero** [comment]
shippit

**Comment by Binero** [comment]
Good catch. I am afraid I am not familiar enough with secure chat or velocity to be able to fix this.

**Comment by Binero** [comment]
Ah I see what bug you mean. It happens when players do `/kick` or `/ban`. This bug was already present in 1.19.2.

**Comment by Binero** [comment]
Can confirm the existing bug became a lot worse.

**Comment by Binero** [comment]
Latest velocity version fixed it entirely for me.

**Comment by james58899** [comment]
Secure chat is still not fully working, temporarily converting all chats to system messages.

**Pull request merged**
